---
- name: Install Docker on Debian
  hosts: all
  gather_facts: true
  become: true

  roles:
    - docker

  tasks:
    - name: Check Docker version
      ansible.builtin.command: docker --version
      register: docker_version
      changed_when: false

    - name: Display Docker version
      ansible.builtin.debug:
        var: docker_version.stdout
